Created the Henry Ford page
abel-tefera/past-project-fcc pull request #1
Opened 2023-02-20 08:19 UTC by abel-tefera

### Summary

- Created the index.html page for displaying Henry Ford's  bio
- Created the index.css file for styling based on the fcc guidelines
- Created an MIT license for this project

2023-02-20 08:31 UTC, abel-tefera commented on css/style.css
> +/* Styling the body element
You should remove all comments in your code. Comments should not end up in the production code.

2023-02-20 08:32 UTC, abel-tefera commented on js/index.js
> +// !! IMPORTANT README:
Please remove the js file as it's not part of this project

2023-02-20 08:32 UTC, abel-tefera commented on README.md
> -# past-project-fcc
Kindly set up linters in your project

2023-02-20 09:13 UTC, brainconnect93 requested changes
### Hi @abel-tefera, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif">

### To Highlight :1st_place_medal: 
- Proper Usage of the Github review feature ✔️ 
- Use Of Gif ✔️
- Use of inline comment ✔️


### Changes Required

- [x] Well done making use of an inline comment in your review, but i would kindly suggest you  include an explanation for `WHY` you request those changes
E.G:

- The student always includes an explanation, a "why", for each requested change. For example:
   - This is a well-explained request: Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible
   - This request lacks a "why": Why don't you use an article tag here instead of a div?

- [x] Also i would suggest you make your comment clear and understandable:
- The student comments are clear and easy to understand. For Example:
   - This is a clear comment: *The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?*
   - This is a vague comment: *The README is not descriptive, why don't you make it better?* 

- [x] [Optional]  I would kindly suggest you make use of friendly `gif` in your in your general review message the way reviewers do use it in their reviews, as this gives your review a kind of friendly attraction to the author of the project you are reviewing.


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 06:36 UTC, abel-tefera commented
Hi @abel-tefera 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights


Proper Usage of the Github review feature ✔️
Use Of Gif ✔️
Use of inline comment ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 07:01 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @abel-tefera , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ Good use of in-comment
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 07:26 UTC, merged